excel_upload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace="myapp")),
]

myapp/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = "myapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('api/checked', views.result_list),
    path('api/site_check/<url>', views.detail),
]

myapp/models.py
from django.db import models

# Create your models here.

# class Url(models.Model):
#     """ Model representing url """
#     url = models.URLField(blank=False)

#     def __str__(self):
#         """String for representing the Model object."""
#         return self.url

class WebResult(models.Model):
    """ Model representing website check result"""
    url = models.CharField(primary_key=True, unique=True, blank=False, max_length=1000)
    http_code = models.CharField(max_length=250, blank=True)
    datetime = models.DateTimeField(auto_now_add=True, blank=False)
    ip = models.CharField(max_length=100, blank=True)
    timeout = models.FloatField(blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.url + "\nhttp_code: " + str(self.http_code) + "\ndate_time: " + str(self.datetime) +"\nip: " + self.ip + "\ntimeout: " + str(self.timeout)

myapp/views.py
from django.shortcuts import render
from .dbHelper import create_connection, get_all_rows, drop_table_if_exists, migrate_excel_to_sqlite, process_url
from .serializers import WebSerializer
import requests
import time, datetime
from django.http import HttpResponse
from .models import WebResult
from rest_framework import viewsets, status
from rest_framework.response import Response
from django.http import JsonResponse
from django.core import serializers


def index(request):
    """ home page to load excel file """
    if request.method=='GET':
        return render(request, 'myapp/index.html', {})
    else:
        excel_file = request.FILES['excel_file']

        #  validate xlsx file extension
        if excel_file.split(".")[-1] != 'xlsx' or excel_file.split(".")[-1] != 'xls':
            return render(request, 'myapp/index.html', {})

        conn = create_connection('./db.sqlite3')
        drop_table_if_exists(conn, 'url')

        migrate_excel_to_sqlite(conn, excel_file)
        excel_data = get_all_rows(conn, 'url')

        #perform importing / checking of provided urls
        for url in excel_data:
            if WebResult.objects.all().filter(pk=url[0]).exists():
                continue
            if url is not None:
                process_url(conn, url)

        results = get_all_rows(conn, 'myapp_webresult')

        return render(request, 'myapp/index.html', {'results':results})


def detail(request, url):
    """ show details of a website """
    try:
        website = WebResult.objects.get(url=url)
    except WebResult.DoesNotExist:
        return HttpResponse("<h1>This url was not processed. Make sure you type host:port_number:api/site_check/some_url</h1>")

    website = WebResult.objects.get(url=url)
    data = {
        'url': website.url,
        'http_code': website.http_code,
        'ip': website.ip,
        'datetime': website.datetime,
        'timeout': website.timeout
    }
    return JsonResponse(data)


def result_list(request):
    """ show list of checked websites """
    results = WebResult.objects.all()
    data = list()
    d = list()

    d.append("url")
    d.append("http_code")
    d.append("ip")
    d.append("datetime")
    d.append("timeout")
    data.append(d)

    for r in results:
        d = list()
        d.append(r.url)
        d.append(r.http_code)
        d.append(r.ip)
        d.append(r.datetime)
        d.append(r.timeout)
        data.append(d)

    return render(request, 'myapp/list_view.html', {'results':data})

myapp/templates/myapp/index.html
<html>
    <head>
        <title>
            Web site check project
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "myapp:index" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in results %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>

myapp/templates/myapp/list_view.html
<html>
    <head>
        <title>
            List of Checked websites
        </title>
    </head>
    <style>
        table {
          border-spacing: 0;
          width: 100%;
          border: 1px solid #ddd;
        }
        
        th, td {
          text-align: left;
          padding: 6px;
        }
    </style>

    <body>
        <h1>List of Checked websites:</h1>
        <p></p>
        <hr>
        <p>Click the button to sort the table alphabetically, by url name:</p>
        <p><button onclick="sortTable()">Sort</button></p>
        <table id="myTable">
            
            {% for row in results %}
            <tr>
                
                {% for cell in row %}
                    <td>{{ cell }}</td>
                {% endfor %}
            </tr>            
                
            {% endfor %}
        </table>
        
    </body>
    <script>
        function sortTable() {
          var table, rows, switching, i, x, y, shouldSwitch;
          table = document.getElementById("myTable");
          switching = true;
          /*Make a loop that will continue until
          no switching has been done:*/
          while (switching) {
            //start by saying: no switching is done:
            switching = false;
            rows = table.rows;
            /*Loop through all table rows (except the
            first, which contains table headers):*/
            for (i = 1; i < (rows.length - 1); i++) {
              //start by saying there should be no switching:
              shouldSwitch = false;
              /*Get the two elements you want to compare,
              one from current row and one from the next:*/
              x = rows[i].getElementsByTagName("TD")[0];
              y = rows[i + 1].getElementsByTagName("TD")[0];
              //check if the two rows should switch place:
              if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                //if so, mark as a switch and break the loop:
                shouldSwitch = true;
                break;
              }
            }
            if (shouldSwitch) {
              /*If a switch has been marked, make the switch
              and mark that a switch has been done:*/
              rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
              switching = true;
            }
          }
        }
        </script>
</html>